### ISSUE TITLE
Error running karma start

### ISSUE THREAD

**Issue by Sigfried** [Swizec/react-testing-example#1]
webpack is installed (can run it in this directory without a problem), npm install works fine.

```
⇒  karma start
07 10 2015 14:10:55.734:WARN [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:mocha"! (Resolving: framework:mocha)
    at error (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /usr/local/lib/node_modules/karma/lib/server.js:137:20
    at Array.forEach (native)
    at Server._start (/usr/local/lib/node_modules/karma/lib/server.js:136:21)
    at invoke (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.start (/usr/local/lib/node_modules/karma/lib/server.js:101:18)
    at Object.exports.run (/usr/local/lib/node_modules/karma/lib/cli.js:231:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
```

**Comment by Sigfried** [comment]
I upgraded various things and now I get

```
⇒  karma start
[1]    4077 segmentation fault  karma start
```

**Comment by zawarudo** [comment]
I also ran into karma issues,

all I had to do was bump karma to 0.13.0

Maybe this will help you?

``` javascript
  "devDependencies": {
    "babel-core": "^5.2.17",
    "babel-loader": "^5.0.0",
    "d3": "^3.5.5",
    "expect": "^1.6.0",
    "jsx-loader": "^0.13.2",
    "karma": "^0.13.0",
    "karma-chrome-launcher": "^0.1.10",
    "karma-cli": "0.0.4",
    "karma-mocha": "^0.1.10",
    "karma-sourcemap-loader": "^0.3.4",
    "karma-webpack": "^1.5.1",
    "mocha": "^2.2.4",
    "react": "^0.13.3",
    "react-hot-loader": "^1.2.7",
    "react-tools": "^0.13.3",
    "webpack": "^1.9.4",
    "webpack-dev-server": "^1.8.2"
  },
```

**Comment by danielfahy** [comment]
Thanks @zawarudo 
I can't use `karma start` but I can use `npm test` after I changed the version of karma from
`"karma": "^0.12.31",` to 
`"karma": "^0.13.0",` 
in package.json

**Comment by danielfahy** [comment]
Also you need to install the karma command line interface on your machine if you want to use `karma start`

Do this with `sudo npm install -g karma-cli`

**Comment by JerJohn15** [comment]
danielfahy's answer worked for me, but now I'm having problems with some of the tests performing, in particular, getting **ScatterPlot** and **RandomPicker** to work in the TestUtils.renderIntoDocument method. Upon running "karma start", I get **Unexpected token at '<'** errors:

``` npm
WARNING in ./src/__tests__/RandomPicker-test.jsx
Module build failed: SyntaxError: G:/Programming Projects/GitHub/react-testing-example/src/__tests__/RandomPicker-test.jsx: Unexpected token (10:12)
   8 |     it("loads without error", function () {
   9 |         var picker = TestUtils.renderIntoDocument(
> 10 |             <RandomPicker />
     |             ^
  11 |         );
  12 |
  13 |         expect(picker).toExist();

WARNING in ./src/__tests__/ScatterPlot-test.jsx
Module build failed: SyntaxError: G:/Programming Projects/GitHub/react-testing-example/src/__tests__/ScatterPlot-test.jsx: Unexpected token (19:12)
  17 |     it("renders an h1", function () {
  18 |         var scatterplot = TestUtils.renderIntoDocument(
> 19 |             <ScatterPlot />
     |             ^
  20 |         );
  21 |
  22 |         var h1 = TestUtils.findRenderedDOMComponentWithTag(


```

I haven't found a specific solution to this problem online yet, just wondering if anyone else here has resolved this.

**Comment by dysthayes** [comment]
I'm running into the syntax error too. Wonder anyone has solved the issue?
